### ISSUE TITLE
Adding an exclusion option to `wp core verify-checksums` ?

### ISSUE THREAD

**Issue by kanlukasz** [wp-cli/checksum-command#117] opened 2023-09-04 17:14 UTC
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I am using `wp core verify-checksums` as a cron job to check the checksums every night.
I have some additional files that are returned as `Warning`, eg.:
```
Warning: File should not exist: wp-admin/.htaccess
Warning: File should not exist: wp-includes/.htaccess
Warning: File should not exist: wp-config-external.php
Success: WordPress installation verifies against checksums.
```
I create daily e-mail reports based on what this command returns, so these warnings are problematic. I currently workaround this with the `sed` command, but it would be much better if there was a flag such as `--exclude`.

**Describe the solution you'd like**
```
wp core verify-checksums --exclude=<file>
```
What do you think? Is this even possible?

**Comment by danielbachhuber** [comment] 2023-09-07 20:33
Thanks for the suggestion, @kanlukasz 

This looks like a duplicate of https://github.com/wp-cli/checksum-command/issues/64

**Closed by danielbachhuber** 2023-09-07 20:33 UTC
